modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "subtleskybox"
version = "${version}"
displayName = "Subtle Skybox"
authors = "jaskarth"
description = '''
Subtle changes to the skybox while keeping it vanilla-style.
'''
logoFile = "assets/subtleskybox/icon.png"

[[mixins]]
config = "subtleskybox.mixins.json"

[[dependencies.subtleskybox]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.subtleskybox]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"
